### PR TITLE
Small fix for the Local Storage fix.

### PR DESCRIPTION
**Pull request by Kezxo**
Seems like I messed up a bit when I did #3 , sorry about that.
It should either be `http*.*` like it is on the tron version or possibly `http*`, not `http*.`

### CODE REVIEW

**Comment by Kezxo** [comment]
Is it just me or do these files not show up in the log file? Is that intended?

**Comment by vocatus** [comment]
Merging, thanks. 

What do you mean about files not showing up in the log file?

**Comment by Kezxo** [comment]
It deletes the local storage files like it should but it's not logged in the logfile.

**Comment by vocatus** [comment]
@Kezxo : fixed, see latest commit and changelog comment in script header.

**Comment by Kezxo** [comment]
Great, thanks! :+1:

**Pull request merged**
